Texture debugtex;
Texture icon_lightbulb;
Texture npc_john;
Texture npc_john_hurt;
Texture tex_ball;
Texture tex_brick;
Texture tex_checker;
Texture tex_concretewall;
Texture tex_crate_c;
Texture tex_error;
Texture tex_grass;
Texture tex_lava;
Texture tex_mark;
Texture tex_obj_barrel;
Texture tex_rockwall;
Texture tex_scifi_floortile;
Texture tex_stone;
Texture tex_wooddoor;
Texture tex_woodfloor;

void InitTextures() {
	debugtex = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/debugtex.png");
	icon_lightbulb = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/icon_lightbulb.png");
	npc_john = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/npc_john.png");
	npc_john_hurt = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/npc_john_hurt.png");
	tex_ball = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_ball.png");
	tex_brick = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_brick.jpg");
	tex_checker = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_checker.png");
	tex_concretewall = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_concretewall.jpg");
	tex_crate_c = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_crate_c.png");
	tex_error = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_error.png");
	tex_grass = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_grass.png");
	tex_lava = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_lava.png");
	tex_mark = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_mark.png");
	tex_obj_barrel = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_obj_barrel.png");
	tex_rockwall = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_rockwall.png");
	tex_scifi_floortile = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_scifi_floortile.jpg");
	tex_stone = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_stone.jpg");
	tex_wooddoor = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_wooddoor.png");
	tex_woodfloor = LoadTexture("c:/Users/rolan/OneDrive/Documents/Roland C++/UniRaylib2/UniRaylib/assets/textures/tex_woodfloor.png");
}
void UnloadTextures() {
	UnloadTexture(debugtex);
	UnloadTexture(icon_lightbulb);
	UnloadTexture(npc_john);
	UnloadTexture(npc_john_hurt);
	UnloadTexture(tex_ball);
	UnloadTexture(tex_brick);
	UnloadTexture(tex_checker);
	UnloadTexture(tex_concretewall);
	UnloadTexture(tex_crate_c);
	UnloadTexture(tex_error);
	UnloadTexture(tex_grass);
	UnloadTexture(tex_lava);
	UnloadTexture(tex_mark);
	UnloadTexture(tex_obj_barrel);
	UnloadTexture(tex_rockwall);
	UnloadTexture(tex_scifi_floortile);
	UnloadTexture(tex_stone);
	UnloadTexture(tex_wooddoor);
	UnloadTexture(tex_woodfloor);
}